name: 'build ghost-core (x86_64-linux-gnu)'

on: [push]

jobs:
  build-macos:
    runs-on: macOS-11
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-build-
      - name: Xcode Select
        # You may pin to the exact commit or the version.
        # uses: devbotsxyz/xcode-select@05f94658217eb8575f0aabd3b95e702a47995d21
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          # Version to use (like '11.7', '12' or simply 'latest')
          version: 12.4
     
     
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@1.1 automake libtool boost miniupnpc pkg-config python qt libevent qrencode protobuf hidapi librsvg sqlite berkeley-db4
  
      - name: Refresh automake configs
        run: ./autogen.sh

      - name: Configure automake
        run: ./configure --prefix=`pwd`/depends/${{ runner.os }} --with-gui=auto

      - name: Build codebase
        run: make -j4
        
      - name: Unittests
        run: make check
